name: Check Docker Compose development environment
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      - name: Build the stack
        run: docker-compose up -d

      - name: Setup environment file with database settings
        run: cp .env.example .env

      - name: Wait for MariaDB to come up 
        run: sleep 30

      - name: Test WordPress is running successfully
        run: curl -s --retry-delay 5 --retry 5 --retry-connrefused http://localhost:8082/